version: '3.9'

services:
  frontend:
    image: "ghcr.io/chheangg/karas-frontend:latest"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_API_URL
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
    - nginx_network
networks:
  nginx_network:
    external: true