version: '3.9'

services:
  frontend:
    image: "ghcr.io/chheangg/karas-frontend:latest"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=5173
      - VITE_BACKEND_API_URL=${{ secrets.VITE_BACKEND_API_URL }}
      - VITE_KEYCLOAK_URL=${{ secrets.VITE_KEYCLOAK_URL }}
      - VITE_MINIO_URL=${{ secrets.VITE_MINIO_URL }}
      - VITE_BUCKET_NAME=${{ secrets.VITE_BUCKET_NAME }}
      - VITE_CLIENT_ID=${{ secrets.VITE_CLIENT_ID }}
      - VITE_AUTHORITY=${{ secrets.VITE_AUTHORITY }}
      - VITE_SHOW_DEV_TOOLS=${{ secrets.VITE_SHOW_DEV_TOOLS }}
      - HOSTNAME=${{ secrets.HOSTNAME }}
      - MINIO_HOSTNAME=${{ secrets.MINIO_HOSTNAME }}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - nginx_network

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
networks:
  nginx_network:
    external: true