/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as DashboardlayoutImport } from './routes/_dashboard_layout'
import { Route as DashboardlayoutIndexImport } from './routes/_dashboard_layout/index'
import { Route as DashboardlayoutSalesRouteImport } from './routes/_dashboard_layout/sales/route'
import { Route as DashboardlayoutMaintenanceIndexImport } from './routes/_dashboard_layout/maintenance/index'
import { Route as DashboardlayoutInventoryIndexImport } from './routes/_dashboard_layout/inventory/index'
import { Route as DashboardlayoutInventoryInventorylayoutImport } from './routes/_dashboard_layout/inventory/_inventory_layout'
import { Route as DashboardlayoutInventoryUnitsCreateImport } from './routes/_dashboard_layout/inventory/units/create'
import { Route as DashboardlayoutInventoryProductsCreateImport } from './routes/_dashboard_layout/inventory/products/create'
import { Route as DashboardlayoutInventoryCategoriesCreateImport } from './routes/_dashboard_layout/inventory/categories/create'
import { Route as DashboardlayoutInventoryInventorylayoutUnitsIndexImport } from './routes/_dashboard_layout/inventory/_inventory_layout/units/index'
import { Route as DashboardlayoutInventoryInventorylayoutProductsIndexImport } from './routes/_dashboard_layout/inventory/_inventory_layout/products/index'
import { Route as DashboardlayoutInventoryInventorylayoutCategoriesIndexImport } from './routes/_dashboard_layout/inventory/_inventory_layout/categories/index'
import { Route as DashboardlayoutInventoryUnitsEditUnitIdImport } from './routes/_dashboard_layout/inventory/units/edit/$unitId'
import { Route as DashboardlayoutInventoryProductsEditProductIdImport } from './routes/_dashboard_layout/inventory/products/edit/$productId'
import { Route as DashboardlayoutInventoryCategoriesEditCategoryIdImport } from './routes/_dashboard_layout/inventory/categories/edit/$categoryId'

// Create Virtual Routes

const DashboardlayoutInventoryImport = createFileRoute(
  '/_dashboard_layout/inventory',
)()

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const DashboardlayoutRoute = DashboardlayoutImport.update({
  id: '/_dashboard_layout',
  getParentRoute: () => rootRoute,
} as any)

const DashboardlayoutInventoryRoute = DashboardlayoutInventoryImport.update({
  path: '/inventory',
  getParentRoute: () => DashboardlayoutRoute,
} as any)

const DashboardlayoutIndexRoute = DashboardlayoutIndexImport.update({
  path: '/',
  getParentRoute: () => DashboardlayoutRoute,
} as any)

const DashboardlayoutSalesRouteRoute = DashboardlayoutSalesRouteImport.update({
  path: '/sales',
  getParentRoute: () => DashboardlayoutRoute,
} as any)

const DashboardlayoutMaintenanceIndexRoute =
  DashboardlayoutMaintenanceIndexImport.update({
    path: '/maintenance/',
    getParentRoute: () => DashboardlayoutRoute,
  } as any)

const DashboardlayoutInventoryIndexRoute =
  DashboardlayoutInventoryIndexImport.update({
    path: '/',
    getParentRoute: () => DashboardlayoutInventoryRoute,
  } as any)

const DashboardlayoutInventoryInventorylayoutRoute =
  DashboardlayoutInventoryInventorylayoutImport.update({
    id: '/_inventory_layout',
    getParentRoute: () => DashboardlayoutInventoryRoute,
  } as any)

const DashboardlayoutInventoryUnitsCreateRoute =
  DashboardlayoutInventoryUnitsCreateImport.update({
    path: '/units/create',
    getParentRoute: () => DashboardlayoutInventoryRoute,
  } as any)

const DashboardlayoutInventoryProductsCreateRoute =
  DashboardlayoutInventoryProductsCreateImport.update({
    path: '/products/create',
    getParentRoute: () => DashboardlayoutInventoryRoute,
  } as any)

const DashboardlayoutInventoryCategoriesCreateRoute =
  DashboardlayoutInventoryCategoriesCreateImport.update({
    path: '/categories/create',
    getParentRoute: () => DashboardlayoutInventoryRoute,
  } as any)

const DashboardlayoutInventoryInventorylayoutUnitsIndexRoute =
  DashboardlayoutInventoryInventorylayoutUnitsIndexImport.update({
    path: '/units/',
    getParentRoute: () => DashboardlayoutInventoryInventorylayoutRoute,
  } as any)

const DashboardlayoutInventoryInventorylayoutProductsIndexRoute =
  DashboardlayoutInventoryInventorylayoutProductsIndexImport.update({
    path: '/products/',
    getParentRoute: () => DashboardlayoutInventoryInventorylayoutRoute,
  } as any)

const DashboardlayoutInventoryInventorylayoutCategoriesIndexRoute =
  DashboardlayoutInventoryInventorylayoutCategoriesIndexImport.update({
    path: '/categories/',
    getParentRoute: () => DashboardlayoutInventoryInventorylayoutRoute,
  } as any)

const DashboardlayoutInventoryUnitsEditUnitIdRoute =
  DashboardlayoutInventoryUnitsEditUnitIdImport.update({
    path: '/units/edit/$unitId',
    getParentRoute: () => DashboardlayoutInventoryRoute,
  } as any)

const DashboardlayoutInventoryProductsEditProductIdRoute =
  DashboardlayoutInventoryProductsEditProductIdImport.update({
    path: '/products/edit/$productId',
    getParentRoute: () => DashboardlayoutInventoryRoute,
  } as any)

const DashboardlayoutInventoryCategoriesEditCategoryIdRoute =
  DashboardlayoutInventoryCategoriesEditCategoryIdImport.update({
    path: '/categories/edit/$categoryId',
    getParentRoute: () => DashboardlayoutInventoryRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard_layout': {
      id: '/_dashboard_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardlayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_dashboard_layout/sales': {
      id: '/_dashboard_layout/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof DashboardlayoutSalesRouteImport
      parentRoute: typeof DashboardlayoutImport
    }
    '/_dashboard_layout/': {
      id: '/_dashboard_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardlayoutIndexImport
      parentRoute: typeof DashboardlayoutImport
    }
    '/_dashboard_layout/inventory': {
      id: '/_dashboard_layout/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof DashboardlayoutInventoryImport
      parentRoute: typeof DashboardlayoutImport
    }
    '/_dashboard_layout/inventory/_inventory_layout': {
      id: '/_dashboard_layout/inventory/_inventory_layout'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof DashboardlayoutInventoryInventorylayoutImport
      parentRoute: typeof DashboardlayoutInventoryRoute
    }
    '/_dashboard_layout/inventory/': {
      id: '/_dashboard_layout/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof DashboardlayoutInventoryIndexImport
      parentRoute: typeof DashboardlayoutInventoryImport
    }
    '/_dashboard_layout/maintenance/': {
      id: '/_dashboard_layout/maintenance/'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof DashboardlayoutMaintenanceIndexImport
      parentRoute: typeof DashboardlayoutImport
    }
    '/_dashboard_layout/inventory/categories/create': {
      id: '/_dashboard_layout/inventory/categories/create'
      path: '/categories/create'
      fullPath: '/inventory/categories/create'
      preLoaderRoute: typeof DashboardlayoutInventoryCategoriesCreateImport
      parentRoute: typeof DashboardlayoutInventoryImport
    }
    '/_dashboard_layout/inventory/products/create': {
      id: '/_dashboard_layout/inventory/products/create'
      path: '/products/create'
      fullPath: '/inventory/products/create'
      preLoaderRoute: typeof DashboardlayoutInventoryProductsCreateImport
      parentRoute: typeof DashboardlayoutInventoryImport
    }
    '/_dashboard_layout/inventory/units/create': {
      id: '/_dashboard_layout/inventory/units/create'
      path: '/units/create'
      fullPath: '/inventory/units/create'
      preLoaderRoute: typeof DashboardlayoutInventoryUnitsCreateImport
      parentRoute: typeof DashboardlayoutInventoryImport
    }
    '/_dashboard_layout/inventory/categories/edit/$categoryId': {
      id: '/_dashboard_layout/inventory/categories/edit/$categoryId'
      path: '/categories/edit/$categoryId'
      fullPath: '/inventory/categories/edit/$categoryId'
      preLoaderRoute: typeof DashboardlayoutInventoryCategoriesEditCategoryIdImport
      parentRoute: typeof DashboardlayoutInventoryImport
    }
    '/_dashboard_layout/inventory/products/edit/$productId': {
      id: '/_dashboard_layout/inventory/products/edit/$productId'
      path: '/products/edit/$productId'
      fullPath: '/inventory/products/edit/$productId'
      preLoaderRoute: typeof DashboardlayoutInventoryProductsEditProductIdImport
      parentRoute: typeof DashboardlayoutInventoryImport
    }
    '/_dashboard_layout/inventory/units/edit/$unitId': {
      id: '/_dashboard_layout/inventory/units/edit/$unitId'
      path: '/units/edit/$unitId'
      fullPath: '/inventory/units/edit/$unitId'
      preLoaderRoute: typeof DashboardlayoutInventoryUnitsEditUnitIdImport
      parentRoute: typeof DashboardlayoutInventoryImport
    }
    '/_dashboard_layout/inventory/_inventory_layout/categories/': {
      id: '/_dashboard_layout/inventory/_inventory_layout/categories/'
      path: '/categories'
      fullPath: '/inventory/categories'
      preLoaderRoute: typeof DashboardlayoutInventoryInventorylayoutCategoriesIndexImport
      parentRoute: typeof DashboardlayoutInventoryInventorylayoutImport
    }
    '/_dashboard_layout/inventory/_inventory_layout/products/': {
      id: '/_dashboard_layout/inventory/_inventory_layout/products/'
      path: '/products'
      fullPath: '/inventory/products'
      preLoaderRoute: typeof DashboardlayoutInventoryInventorylayoutProductsIndexImport
      parentRoute: typeof DashboardlayoutInventoryInventorylayoutImport
    }
    '/_dashboard_layout/inventory/_inventory_layout/units/': {
      id: '/_dashboard_layout/inventory/_inventory_layout/units/'
      path: '/units'
      fullPath: '/inventory/units'
      preLoaderRoute: typeof DashboardlayoutInventoryInventorylayoutUnitsIndexImport
      parentRoute: typeof DashboardlayoutInventoryInventorylayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  DashboardlayoutRoute: DashboardlayoutRoute.addChildren({
    DashboardlayoutSalesRouteRoute,
    DashboardlayoutIndexRoute,
    DashboardlayoutInventoryRoute: DashboardlayoutInventoryRoute.addChildren({
      DashboardlayoutInventoryInventorylayoutRoute:
        DashboardlayoutInventoryInventorylayoutRoute.addChildren({
          DashboardlayoutInventoryInventorylayoutCategoriesIndexRoute,
          DashboardlayoutInventoryInventorylayoutProductsIndexRoute,
          DashboardlayoutInventoryInventorylayoutUnitsIndexRoute,
        }),
      DashboardlayoutInventoryIndexRoute,
      DashboardlayoutInventoryCategoriesCreateRoute,
      DashboardlayoutInventoryProductsCreateRoute,
      DashboardlayoutInventoryUnitsCreateRoute,
      DashboardlayoutInventoryCategoriesEditCategoryIdRoute,
      DashboardlayoutInventoryProductsEditProductIdRoute,
      DashboardlayoutInventoryUnitsEditUnitIdRoute,
    }),
    DashboardlayoutMaintenanceIndexRoute,
  }),
  LoginRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_dashboard_layout",
        "/login"
      ]
    },
    "/_dashboard_layout": {
      "filePath": "_dashboard_layout.tsx",
      "children": [
        "/_dashboard_layout/sales",
        "/_dashboard_layout/",
        "/_dashboard_layout/inventory",
        "/_dashboard_layout/maintenance/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_dashboard_layout/sales": {
      "filePath": "_dashboard_layout/sales/route.tsx",
      "parent": "/_dashboard_layout"
    },
    "/_dashboard_layout/": {
      "filePath": "_dashboard_layout/index.tsx",
      "parent": "/_dashboard_layout"
    },
    "/_dashboard_layout/inventory": {
      "filePath": "_dashboard_layout/inventory",
      "parent": "/_dashboard_layout",
      "children": [
        "/_dashboard_layout/inventory/_inventory_layout",
        "/_dashboard_layout/inventory/",
        "/_dashboard_layout/inventory/categories/create",
        "/_dashboard_layout/inventory/products/create",
        "/_dashboard_layout/inventory/units/create",
        "/_dashboard_layout/inventory/categories/edit/$categoryId",
        "/_dashboard_layout/inventory/products/edit/$productId",
        "/_dashboard_layout/inventory/units/edit/$unitId"
      ]
    },
    "/_dashboard_layout/inventory/_inventory_layout": {
      "filePath": "_dashboard_layout/inventory/_inventory_layout.tsx",
      "parent": "/_dashboard_layout/inventory",
      "children": [
        "/_dashboard_layout/inventory/_inventory_layout/categories/",
        "/_dashboard_layout/inventory/_inventory_layout/products/",
        "/_dashboard_layout/inventory/_inventory_layout/units/"
      ]
    },
    "/_dashboard_layout/inventory/": {
      "filePath": "_dashboard_layout/inventory/index.tsx",
      "parent": "/_dashboard_layout/inventory"
    },
    "/_dashboard_layout/maintenance/": {
      "filePath": "_dashboard_layout/maintenance/index.tsx",
      "parent": "/_dashboard_layout"
    },
    "/_dashboard_layout/inventory/categories/create": {
      "filePath": "_dashboard_layout/inventory/categories/create.tsx",
      "parent": "/_dashboard_layout/inventory"
    },
    "/_dashboard_layout/inventory/products/create": {
      "filePath": "_dashboard_layout/inventory/products/create.tsx",
      "parent": "/_dashboard_layout/inventory"
    },
    "/_dashboard_layout/inventory/units/create": {
      "filePath": "_dashboard_layout/inventory/units/create.tsx",
      "parent": "/_dashboard_layout/inventory"
    },
    "/_dashboard_layout/inventory/categories/edit/$categoryId": {
      "filePath": "_dashboard_layout/inventory/categories/edit/$categoryId.tsx",
      "parent": "/_dashboard_layout/inventory"
    },
    "/_dashboard_layout/inventory/products/edit/$productId": {
      "filePath": "_dashboard_layout/inventory/products/edit/$productId.tsx",
      "parent": "/_dashboard_layout/inventory"
    },
    "/_dashboard_layout/inventory/units/edit/$unitId": {
      "filePath": "_dashboard_layout/inventory/units/edit/$unitId.tsx",
      "parent": "/_dashboard_layout/inventory"
    },
    "/_dashboard_layout/inventory/_inventory_layout/categories/": {
      "filePath": "_dashboard_layout/inventory/_inventory_layout/categories/index.tsx",
      "parent": "/_dashboard_layout/inventory/_inventory_layout"
    },
    "/_dashboard_layout/inventory/_inventory_layout/products/": {
      "filePath": "_dashboard_layout/inventory/_inventory_layout/products/index.tsx",
      "parent": "/_dashboard_layout/inventory/_inventory_layout"
    },
    "/_dashboard_layout/inventory/_inventory_layout/units/": {
      "filePath": "_dashboard_layout/inventory/_inventory_layout/units/index.tsx",
      "parent": "/_dashboard_layout/inventory/_inventory_layout"
    }
  }
}
ROUTE_MANIFEST_END */
