/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HelloWorldRouteImport } from './routes/hello-world/route'

// Create/Update Routes

const HelloWorldRouteRoute = HelloWorldRouteImport.update({
  path: '/hello-world',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/hello-world': {
      id: '/hello-world'
      path: '/hello-world'
      fullPath: '/hello-world'
      preLoaderRoute: typeof HelloWorldRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({ HelloWorldRouteRoute })

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/hello-world"
      ]
    },
    "/hello-world": {
      "filePath": "hello-world/route.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
