name: Build and deploy frontend to Digital Ocean
run-name: ${{ github.actor }} is deploying to development server 🚀
on:
  push:
    branches:
      - development
jobs:
  build-and-publish:
    name: build and publish image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login
        run: |
          echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and Publish
        run: |
          echo ${{ secrets.PROD_ENV_FILE }} > .env
          docker compose -f docker-compose.yml build --no-cache
          docker compose -f docker-compose.yml push
  deployment:
    needs: build-and-publish
    name: deploy image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: rsync docker compose config
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: docker-compose.yml
          remote_path: karas-frontend
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: rsync nginx.conf
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: nginx.conf
          remote_path: karas-frontend
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: connect and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker system prune -a --volumes
            docker network create nginx_network
            cd karas-frontend
            echo "${{ secrets.CR_PAT }}" | docker login ghcr.io --username "${{ github.repository_owner }}" --password-stdin
            docker compose pull
            docker compose up -d
