name: Build and Deploy Frontend to Digital Ocean
run-name: ${{ github.actor }} is deploying to development server 🚀
on:
  push:
    branches:
      - development
jobs:
  DeployToMain:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Frontend application on development server
        uses: appleboy/ssh-action@v1.0.3
        with:
            host: ${{secrets.SSH_HOST}}
            username: ${{secrets.SSH_USERNAME}}
            password: ${{secrets.SSH_PASSWORD}}
            script: |           
              rm -rf karas-frontend
              echo "Clone repo"
              git clone git@github.com:Indraneers/karas-frontend.git
              cd ./karas-frontend
              git checkout development

              echo "Make ENV file"
              touch .env
              echo "${{secrets.PROD_ENV_FILE}}" > .env
              
              echo "Deploy image"
              docker compose down 
              docker compose build --no-cache
              docker compose up -d
          